# Preprocessing Data

In [2]:
# import libraries

import pandas as pd
import numpy as np

### Satisfaction dataset

In [3]:
data = pd.read_csv('../dataset/DCCV_AVQ_PERSONE_12052021103900983.csv')

regioni = ['Italia','Trentino Alto Adige / Südtirol', 'Emilia-Romagna','Toscana','Abruzzo','Piemonte','Lazio', 'Sardegna', 'Calabria','Lombardia', 'Sicilia','Basilicata', 'Puglia', 'Campania','Provincia Autonoma Bolzano / Bozen','Provincia Autonoma Trento', 'Friuli-Venezia Giulia',"Valle d'Aosta / Vallée d'Aoste",'Veneto', 'Marche','Liguria', 'Umbria', 'Molise']
data = data.loc[data['Territorio'].isin(regioni)]
for index, row in data.iterrows():
    if row['TIPO_DATO_AVQ'] in ['0_HFOOD_Q','0_HFOOD_V']:
        data.loc[index,'TIPO_ANALISI'] = 'FOOD'
    if row['TIPO_DATO_AVQ'] in ['0_SANFAC_V','0_SANFAC_Q']:
        data.loc[index,'TIPO_ANALISI'] = 'SANFAC'
    if row['TIPO_DATO_AVQ'] in ['0_NURS_V','0_NURS_Q']:
        data.loc[index,'TIPO_ANALISI'] = 'NURS'
    if row['TIPO_DATO_AVQ'] in ['0_MED_CAREQ','0_MED_CAREV']:
        data.loc[index,'TIPO_ANALISI'] = 'MED_CARE'
data = data[['ITTER107','Territorio','TIPO_ANALISI','Tipo dato','MISURA_AVQ','Misura','TIME','Value']]


for index, row in data.iterrows():
    if row['Tipo dato'] == 'molto ':
        data.loc[index,'value_molto'] = row['Value']
    if row['Tipo dato'] == 'molto e abbastanza':
        data.loc[index,'value_molto&abbastanza'] = row['Value']

del data['Tipo dato']
df = pd.DataFrame()
for index, row in data.iterrows():
    
    if  not (pd.isnull(row['value_molto&abbastanza'])) :
        d = data.loc[data['TIPO_ANALISI'] == row['TIPO_ANALISI']].loc[data['Territorio'] == row['Territorio']].loc[data['MISURA_AVQ'] == row['MISURA_AVQ']].loc[data['TIME'] == row['TIME']].loc[data['value_molto&abbastanza'].isnull()]
        d['value_molto&abbastanza'] = row['value_molto&abbastanza']
        
        df = df.append(d)
    if  not (pd.isnull(row['value_molto'])) :
        b = data.loc[data['TIPO_ANALISI'] == row['TIPO_ANALISI']].loc[data['Territorio'] == row['Territorio']].loc[data['MISURA_AVQ'] == row['MISURA_AVQ']].loc[data['TIME'] == row['TIME']].loc[data['value_molto'].isnull()]
        b['value_molto'] = row['value_molto']
        
        df = df.append(b)
del df['Value']

df = df.drop_duplicates()

df = df[['Territorio','TIPO_ANALISI','MISURA_AVQ','TIME','value_molto&abbastanza','value_molto']]
df['value_abbastanza'] = df['value_molto&abbastanza'] - df['value_molto']
df['value_abbastanza'] = round(df['value_abbastanza'],1)
df = df.loc[df['MISURA_AVQ'] == 'HSC']
df['value_scarso&poco'] = 100 - df['value_molto&abbastanza']
del df['value_molto&abbastanza']
df['value_scarso&poco'] = round(df['value_scarso&poco'],1)
df

,Territorio,TIPO_ANALISI,MISURA_AVQ,TIME,value_molto,value_abbastanza,value_scarso&poco
24,Italia,NURS,HSC,2014,40.0,46.1,13.9
25,Italia,NURS,HSC,2015,40.2,48.9,10.9
26,Italia,NURS,HSC,2016,39.6,50.0,10.4
27,Italia,NURS,HSC,2017,39.5,47.4,13.1
28,Italia,NURS,HSC,2018,39.3,49.7,11.0
...,...,...,...,...,...,...,...
2791,Sicilia,SANFAC,HSC,2015,17.1,48.8,34.1
2792,Sicilia,SANFAC,HSC,2016,13.8,56.2,30.0
2793,Sicilia,SANFAC,HSC,2017,14.7,46.9,38.4
2794,Sicilia,SANFAC,HSC,2018,17.5,51.8,30.7
2795,Sicilia,SANFAC,HSC,2019,7.5,47.2,45.3

In [4]:
soddisfazione = df

In [5]:
soddisfazione

,Territorio,TIPO_ANALISI,MISURA_AVQ,TIME,value_molto,value_abbastanza,value_scarso&poco
24,Italia,NURS,HSC,2014,40.0,46.1,13.9
25,Italia,NURS,HSC,2015,40.2,48.9,10.9
26,Italia,NURS,HSC,2016,39.6,50.0,10.4
27,Italia,NURS,HSC,2017,39.5,47.4,13.1
28,Italia,NURS,HSC,2018,39.3,49.7,11.0
...,...,...,...,...,...,...,...
2791,Sicilia,SANFAC,HSC,2015,17.1,48.8,34.1
2792,Sicilia,SANFAC,HSC,2016,13.8,56.2,30.0
2793,Sicilia,SANFAC,HSC,2017,14.7,46.9,38.4
2794,Sicilia,SANFAC,HSC,2018,17.5,51.8,30.7
2795,Sicilia,SANFAC,HSC,2019,7.5,47.2,45.3

In [ ]:
soddisfazione.to_csv('../dataset/')

### Demografia

In [6]:
data = pd.read_csv('DCIS_RICPOPRES2011_11052021230650636.csv')

regioni = ['Italia','Trentino Alto Adige / Südtirol', 'Emilia-Romagna','Toscana','Abruzzo','Piemonte','Lazio', 'Sardegna', 'Calabria','Lombardia', 'Sicilia','Basilicata', 'Puglia', 'Campania','Provincia Autonoma Bolzano / Bozen','Provincia Autonoma Trento', 'Friuli-Venezia Giulia',"Valle d'Aosta / Vallée d'Aoste",'Veneto', 'Marche','Liguria', 'Umbria', 'Molise']
data = data.loc[data['Territorio'].isin(regioni)]

data = data.loc[data['TIPO_DATO15'] == 'JAN']
data = data.loc[data['CITTADINANZA'] == 'TOTAL']
data = data.loc[data['Sesso'] == 'totale']
data = data[['ITTER107','Territorio','Tipo dato','TIME','Value']]
data = data.loc[data['TIME'].isin([2014,2015,2016,2017,2018,2019])]

In [ ]:
data.to_csv('demografia.csv')

In [7]:
data

      ITTER107 Territorio                  Tipo dato  TIME    Value
52185     ITC1   Piemonte  popolazione al 1º gennaio  2014  4420924
52186     ITC1   Piemonte  popolazione al 1º gennaio  2015  4403562
52187     ITC1   Piemonte  popolazione al 1º gennaio  2016  4384226
52188     ITC1   Piemonte  popolazione al 1º gennaio  2017  4370348
52189     ITC1   Piemonte  popolazione al 1º gennaio  2018  4349911
...        ...        ...                        ...   ...      ...
73894     ITG1    Sicilia  popolazione al 1º gennaio  2015  5028266
73895     ITG1    Sicilia  popolazione al 1º gennaio  2016  5004400
73896     ITG1    Sicilia  popolazione al 1º gennaio  2017  4977900
73897     ITG1    Sicilia  popolazione al 1º gennaio  2018  4942188
73898     ITG1    Sicilia  popolazione al 1º gennaio  2019  4908548

[144 rows x 5 columns]

### Numero ospedali

In [ ]:
data = pd.read_csv('DCIS_OSPED_11052021231523441.csv')

In [ ]:
regioni = ['Italia','Trentino Alto Adige / Südtirol', 'Emilia-Romagna','Toscana','Abruzzo','Piemonte','Lazio', 'Sardegna', 'Calabria','Lombardia', 'Sicilia','Basilicata', 'Puglia', 'Campania','Provincia Autonoma Bolzano / Bozen','Provincia Autonoma Trento', 'Friuli-Venezia Giulia',"Valle d'Aosta / Vallée d'Aoste",'Veneto', 'Marche','Liguria', 'Umbria', 'Molise']
data = data.loc[data['Territorio'].isin(regioni)]
data = data.loc[data['TIPO_DATO14'] == 18]
data = data.loc[data['Tipo di istituto'] == 'totale']
data = data[['ITTER107','Territorio', 'TIME','Value']]

data.to_csv('numero_ospedali.csv')

## adding population, bed hospitals, number of hospitals and healthcare personnel

In [ ]:
soddisfazione

In [ ]:
soddisfazione = soddisfazione[['Territorio','TIPO_ANALISI','TIME','value_molto']]
#soddisfazione = soddisfazione.loc[soddisfazione['TIPO_ANALISI'] == 'NURS']
soddisfazione = soddisfazione.loc[soddisfazione['Territorio'] != 'Italia'].loc[soddisfazione['TIPO_ANALISI'] == 'NURS']

ospedali = pd.read_csv('clean_dataset/numero_ospedali.csv')
ospedali = ospedali[['Territorio','TIME','Value']]
ospedali = ospedali.loc[ospedali['Territorio'] != 'Italia']

soddisfazione = soddisfazione.sort_values(by=['Territorio','TIME'])
ospedali = ospedali.sort_values(by=['Territorio','TIME'])

soddisfazione = soddisfazione.reset_index()
ospedali = ospedali.reset_index()
soddisfazione['numero_ospedali'] = ospedali['Value']
soddisfazione

In [ ]:
demografia = pd.read_csv('clean_dataset/demografia.csv')

demografia = demografia.loc[demografia['Territorio'] != 'Italia']

demografia = demografia.sort_values(by=['Territorio','TIME'])

demografia = demografia[['Territorio','Value', 'TIME']]
demografia = demografia.drop_duplicates()

demografia = demografia.reset_index()

soddisfazione['popolazione'] = demografia['Value']
demografia

In [ ]:
soddisfazione = soddisfazione[['Territorio','TIME','value_molto','numero_ospedali','popolazione']]

data = pd.read_csv('clean_dataset/spese_sanità.csv')
data = data.rename(columns={'Media 2000-2018 ': "Territorio"})
#data = data.loc[data['Media 2000-2018 '].isin()]

regioni = data.Territorio.unique()
data = data.loc[data['Territorio'].isin(regioni)]

In [ ]:
data=data.sort_values(by =  ['Territorio'])

data = data.drop(labels=21, axis=0)
data = data.drop(labels=22, axis=0)
data = data.drop(labels=23, axis=0)
data = data.drop(labels=24, axis=0)
data = data.drop(labels=25, axis=0)

data.iloc[11]['Territorio'] = 'Provincia Autonoma Bolzano / Bozen'
data.iloc[12]['Territorio'] = 'Provincia Autonoma Trento'
data=data.sort_values(by =  ['Territorio'])

lista = []
regioni = data.Territorio.unique()

for i in regioni:
    
    a = data.loc[data['Territorio'] == i]
    a = a.reset_index()
    del a['Territorio']
    del a['index']
    b = list(a.iloc[0])
    
    for h in b:
        lista.append(h)
        
        
soddisfazione = soddisfazione.drop(labels=108, axis=0)
soddisfazione = soddisfazione.drop(labels=109, axis=0)
soddisfazione = soddisfazione.drop(labels=110, axis=0)
soddisfazione = soddisfazione.drop(labels=111, axis=0)
soddisfazione = soddisfazione.drop(labels=112, axis=0)
soddisfazione = soddisfazione.drop(labels=113, axis=0)
soddisfazione=soddisfazione.reset_index()

In [ ]:
lista = [int(l.replace(".", "")) for l in lista]

soddisfazione['investimento'] = lista

del soddisfazione['index']

In [ ]:
soddisfazione

In [ ]:
data = pd.read_csv('postilettocompleto.csv')

In [ ]:
regioni = ['Emilia-Romagna','Toscana','Abruzzo','Piemonte','Lazio', 'Sardegna', 'Calabria','Lombardia', 'Sicilia','Basilicata', 'Puglia', 'Campania','Provincia Autonoma Bolzano / Bozen','Provincia Autonoma Trento', 'Friuli-Venezia Giulia',"Valle d'Aosta / Vallée d'Aoste",'Veneto', 'Marche','Liguria', 'Umbria', 'Molise']

data = data.loc[data['Territorio'].isin(regioni)]

data = data.sort_values(by = ['Territorio', 'TIME'])
data = data.reset_index()

In [ ]:
dea = soddisfazione

In [ ]:
dea['posti_letto'] = data['Value']

In [ ]:
data = pd.read_csv('personalesanitario.csv')

data = data.loc[data['Territorio'].isin(regioni)]
data = data.loc[data['Tipo dato'] == 'personale sanitario']

data = data.sort_values(by = ['Territorio', 'TIME'])
data = data.reset_index()

dea['personale_sanitario'] = data['Value']

dea = dea[['Territorio','TIME','value_molto','numero_ospedali','popolazione','investimento','posti_letto','personale_sanitario']]

### dataset used for DEA

In [ ]:
dea.to_csv('clean_dataset/final_DEA.csv')